name = "ascii_engine"
description = ""
version = "0.1.0-dev"

authors = ["Eli Wynn"]
maintainers = ["Your Name <example@example.com>"]
maintainers-logins = ["github-username"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []