name = "groceries"
description = "For grocery list of honours project requirements"
version = "0.1.0-dev"

authors = ["Eli Wynn"]
maintainers = ["Eli Wynn <example@example.com>"]
maintainers-logins = ["github-username"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["groceries"]
